### PR TITLE
Adding support for mesos-slave metrics and splitting up plugin into master/slave.

### PR DESCRIPTION
**Pull request by rayrod2030**
Based on feedback received in issue https://github.com/rayrod2030/collectd-mesos/issues/4 from @rasputnik this PR adds support for mesos-slaves and also splits the master/slave functionality into two separate plugins.

### CODE REVIEW

**Comment by bobrik** [comment]
First of all: great job! Looking forward to see it merged. I made a dockerized version of your plugin: 

https://github.com/bobrik/docker-collectd-mesos

I found some issues during testing:

* `slave/mem_*` metrics are missing in `mesos-slave` module.

* This should be `gauge`:

```
    'master/uptime_secs': Stat("counter", "master/uptime_secs"),
```

**Comment by bobrik** [comment]
You should add verbose logging to `mesos-master.py` that says something like "not writing data from non-leader", this could save some debugging time.

**Comment by bobrik** [comment]
`master_mem_total` and `master_mem_used` could be reported in bytes, then y axis formatters in tools like grafana would show correct values. Same applies to slave memory metrics.

**Comment by bobrik** [comment]
Conversion to integer kills values like `slave_cpus_percent`: `0.025` becomes `0`.

**Comment by rayrod2030** [comment]
@bobrik Great feedback thank you and I'll work on implementing some of your suggestions and merging this PR.

**Comment by bobrik** [comment]
```
Unhandled python exception in loading module: NameError: global name 'islave_cpus_percentnc' is not defined
```

I'm pretty sure this is not what you intended to do.

**Comment by rayrod2030** [comment]
Thanks for catching that.  Should be fixed now.

**Pull request merged**
